@startuml
class Baker
interface Consumer <<interface>>
class Customer
class DataQueue
class DeliveryGuy
class JsonBaker
class JsonDeliverer
class JsonHandler
class JsonPizzeria
class Main
class Order
class Pizzeria
interface Producer <<interface>>
@enduml